# Generated by Django 3.1.6 on 2021-02-23 00:02

from django.db import migrations, models
import tp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_feed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(null=True, storage=tp.storage_backends.PublicImageStorage(), upload_to=''),
        ),
    ]
