# Generated by Django 3.1.6 on 2021-02-23 05:00

import audio.models
from django.db import migrations, models
import tp.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20210222_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=tp.storage_backends.PublicImageStorage(), upload_to=audio.models.slugify_file_name),
        ),
    ]
