# Generated by Django 3.1.7 on 2021-03-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_episode_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image_license',
            field=models.SmallIntegerField(choices=[(1, 'Public Domain'), (2, 'Unknown'), (3, 'CC BY-SA 2.5'), (4, 'CC BY-SA 3.0')], default=2),
        ),
    ]
