# Generated by Django 3.1.7 on 2021-03-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0011_feed_image_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image_attribution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_attribution_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='image_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='original_image_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
