# Generated by Django 3.1.7 on 2021-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0012_auto_20210316_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image_license_jurisdiction',
            field=models.TextField(default=''),
        ),
    ]
