# Generated by Django 3.1.7 on 2021-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0016_auto_20210316_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='author_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='ebook_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='intro_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='intro_author_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='license',
            field=models.SmallIntegerField(choices=[(1, 'Public Domain'), (2, 'Unknown'), (3, 'CC BY-SA 2.5'), (4, 'CC BY-SA 3.0'), (5, 'CC BY 3.0'), (6, 'CC BY 1.0')], default=1),
        ),
        migrations.AddField(
            model_name='feed',
            name='license_jurisdiction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='translator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feed',
            name='translator_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
