# Generated by Django 3.1.7 on 2021-03-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0018_auto_20210317_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image_license_jurisdiction',
            field=models.TextField(default='(no jurisdiction specified)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image_license_jurisdiction',
            field=models.TextField(default='(no jurisdiction specified)'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='license_jurisdiction',
            field=models.TextField(blank=True, default='(no jurisdiction specified)'),
        ),
    ]
