# Generated by Django 3.1.7 on 2021-03-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0019_auto_20210317_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='intro_author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='intro_author_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='translator',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feed',
            name='translator_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
