# Generated by Django 3.1.7 on 2021-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0020_auto_20210317_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='ebook_title',
            field=models.URLField(default='', max_length=255),
        ),
    ]
