# Generated by Django 3.1.7 on 2021-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0021_feed_ebook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='ebook_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
