# Generated by Django 3.2.10 on 2022-02-18 21:38

import audio.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0024_auto_20211107_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/trent/trentpalmerdotorg/media/audio/images'), upload_to=audio.models.slugify_file_name),
        ),
        migrations.AlterField(
            model_name='episode',
            name='mp3',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/trent/trentpalmerdotorg/media/audio/mp3'), upload_to=audio.models.slugify_file_name),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/trent/trentpalmerdotorg/media/audio/images'), upload_to=audio.models.slugify_file_name),
        ),
    ]
