# Generated by Django 3.1.7 on 2021-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='twitter_handle',
            field=models.CharField(default='@Twitter', max_length=64),
        ),
    ]
