# Generated by Django 3.2.6 on 2021-08-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_twitter_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='totp_key',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
